parameters:
    ez_recommendation.default.yoochoose.customer_id: ~
    ez_recommendation.default.yoochoose.license_key: ~
    ez_recommendation.default.server_uri: ~
    ez_recommendation.default.recommender.included_content_types: ~
    ez_recommendation.default.author_id: 14

    ez_recommendation.api_endpoint: 'https://admin.yoochoose.net'
    ez_recommendation.recommender.api_endpoint: 'http://reco.yoochoose.net'
    ez_recommendation.recommender.consume_timeout: 20
    ez_recommendation.tracking.api_endpoint: 'http://event.yoochoose.net'
    ez_recommendation.tracking.script_url: 'cdn.yoochoose.net/yct.js'
