language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6


# test only master (+ Pull requests)
branches:
  only:
    - master

before_script:
  # Disable xdebug to speed things up as we don't currently generate coverge on travis
  - if [ $TRAVIS_PHP_VERSION != "hhvm" ]; then phpenv config-rm xdebug.ini ; fi
  # Update composer to newest version
  - composer self-update
  # Randomize Symfony versions
  - SYMFONY_VERSIONS=("~2.7.0" "~2.6.0" "")
  - SYMFONY_VERSION=${SYMFONY_VERSIONS["`shuf -i 0-2 -n 1`"]}
  - echo "$SYMFONY_VERSION"
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi;
  # Install packages using composer
  - composer install --dev --prefer-dist
  # Detecting timezone issues by testing on random timezone
  - TEST_TIMEZONES=("America/New_York" "Asia/Calcutta" "UTC")
  - TEST_TIMEZONE=${TEST_TIMEZONES["`shuf -i 0-2 -n 1`"]}
  - echo "$TEST_TIMEZONE"

# execute phpunit as the script command
script: "php -d date.timezone=$TEST_TIMEZONE -d memory_limit=-1 vendor/bin/phpunit"

# disable mail notifications
notifications:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
